# Generated by Django 4.1.1 on 2022-09-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filewordcounts',
            name='text',
            field=models.FileField(upload_to='media/'),
        ),
    ]
