# Generated by Django 4.1.1 on 2022-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_filewordcounts_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filewordcounts',
            name='file',
            field=models.FileField(default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='filewordcounts',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
